package Bomberman;

public enum GameType {
    PLAYER, BOMB, VIRTUAL_BOMB, FLAME, WALL, BRICK, DOOR, BRICK_BREAK,
    POWERUP_BOMBS, POWERUP_FLAMES, POWERUP_SPEED, POWERUP_FLAMEPASS,
    ENEMY1, ENEMY2, ENEMY3, ENEMY4, ENEMY5
}
